// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMsiowc4rAwlQ0nfm_gbqz_4-LLGeyyFE',
    appId: '1:195600237726:android:b8ecde16e394b37f9d278f',
    messagingSenderId: '195600237726',
    projectId: 'medihouse-9deb2',
    storageBucket: 'medihouse-9deb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsLNaiV8DJJLNFVyUAVJwnujL42ARMHF0',
    appId: '1:195600237726:ios:7f0d335f51733b769d278f',
    messagingSenderId: '195600237726',
    projectId: 'medihouse-9deb2',
    storageBucket: 'medihouse-9deb2.firebasestorage.app',
    iosBundleId: 'com.example.mediHouse',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWtbBhbJfnhXiKC3ufUgVBU31gNPSnF6Q',
    appId: '1:195600237726:web:c5baf54c066fb56c9d278f',
    messagingSenderId: '195600237726',
    projectId: 'medihouse-9deb2',
    authDomain: 'medihouse-9deb2.firebaseapp.com',
    storageBucket: 'medihouse-9deb2.firebasestorage.app',
    measurementId: 'G-P2TTR6MEYS',
  );

}